include: package:flutter_lints/flutter.yaml

analyzer:
  errors:
    avoid_print: error
    discarded_futures: error
    unawaited_futures: error

linter:
  rules:
    always_declare_return_types: true
    directives_ordering: true
    prefer_final_locals: true
