name: gmb_scanner_flutter
description: 本产品内部二维码设备适配器。
version: 1.0.0
publish_to: none

environment:
  sdk: ">=3.3.0 <4.0.0"
  flutter: ">=3.22.0"

dependencies:
  flutter:
    sdk: flutter
  mobile_scanner: ^7.1.4

dev_dependencies:
  flutter_lints: ^4.0.0
  flutter_test:
    sdk: flutter
